<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708090430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE projeto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, status VARCHAR(50) DEFAULT NULL, resumo TEXT DEFAULT NULL, data_inicio DATE DEFAULT NULL, data_fim DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE instituicao');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instituicao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(50) DEFAULT NULL, tipo VARCHAR(100) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, site VARCHAR(255) DEFAULT NULL, municipio VARCHAR(150) DEFAULT NULL, uf VARCHAR(2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE projeto');
    }
}
