<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708102439 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instituicao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(50) DEFAULT NULL, tipo VARCHAR(100) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, site VARCHAR(255) DEFAULT NULL, municipio VARCHAR(150) DEFAULT NULL, uf VARCHAR(2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE indicador ADD projeto_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE indicador ADD CONSTRAINT FK_CD123EC343B58490 FOREIGN KEY (projeto_id) REFERENCES projeto (id)');
        $this->addSql('CREATE INDEX IDX_CD123EC343B58490 ON indicador (projeto_id)');
        $this->addSql('ALTER TABLE projeto ADD instituicao_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE projeto ADD CONSTRAINT FK_A0559D94B05E5EEA FOREIGN KEY (instituicao_id) REFERENCES instituicao (id)');
        $this->addSql('CREATE INDEX IDX_A0559D94B05E5EEA ON projeto (instituicao_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE instituicao');
        $this->addSql('ALTER TABLE indicador DROP CONSTRAINT FK_CD123EC343B58490');
        $this->addSql('DROP INDEX IDX_CD123EC343B58490');
        $this->addSql('ALTER TABLE indicador DROP projeto_id');
        $this->addSql('ALTER TABLE projeto DROP CONSTRAINT FK_A0559D94B05E5EEA');
        $this->addSql('DROP INDEX IDX_A0559D94B05E5EEA');
        $this->addSql('ALTER TABLE projeto DROP instituicao_id');
    }
}
