<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260803002000 extends AbstractMigration
{
    public function getDescription(): string { return 'Adiciona propostas de alteração e histórico de moderação.'; }
    public function up(Schema $schema): void
    {
        foreach (['instituicao', 'projeto', 'indicador'] as $table) {
            $this->addSql("ALTER TABLE $table ADD dados_pendentes JSON DEFAULT NULL");
            $this->addSql("ALTER TABLE $table ADD situacao_revisao VARCHAR(20) DEFAULT NULL");
            $this->addSql("ALTER TABLE $table ADD observacao_revisao TEXT DEFAULT NULL");
        }
        $this->addSql('CREATE TABLE cadastro_historico (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, responsavel_id INT DEFAULT NULL, revisor_id INT DEFAULT NULL, tipo VARCHAR(20) NOT NULL, registro_id INT NOT NULL, acao VARCHAR(30) NOT NULL, observacao TEXT DEFAULT NULL, dados JSON DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C021821BB9AF004 ON cadastro_historico (responsavel_id)');
        $this->addSql('CREATE INDEX IDX_4C021821BD3183DF ON cadastro_historico (revisor_id)');
        $this->addSql('CREATE INDEX IDX_CAD_HIST_REG ON cadastro_historico (tipo, registro_id)');
        $this->addSql('ALTER TABLE cadastro_historico ADD CONSTRAINT FK_CAD_HIST_RESP FOREIGN KEY (responsavel_id) REFERENCES app_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cadastro_historico ADD CONSTRAINT FK_CAD_HIST_REV FOREIGN KEY (revisor_id) REFERENCES app_user (id) ON DELETE SET NULL');
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cadastro_historico');
        foreach (['instituicao', 'projeto', 'indicador'] as $table) {
            $this->addSql("ALTER TABLE $table DROP dados_pendentes");
            $this->addSql("ALTER TABLE $table DROP situacao_revisao");
            $this->addSql("ALTER TABLE $table DROP observacao_revisao");
        }
    }
}
